version: "3"

services:
  db:
    container_name: scc_db
    image: $POSTGRES_IMAGE_NAME
    env_file:
      - .env
    ports:
      - $POSTGRES_RUN_PORTS
    networks:
      - $GLOBAL_NETWORK
    volumes:
      - $POSTGRES_RUN_VOLUMES
    environment:
      POSTGRES_USER: $POSTGRES_RUN_ENVIRONMENT_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_RUN_ENVIRONMENT_PASSWORD
      POSTGRES_DB: $POSTGRES_RUN_ENVIRONMENT_DATABASE
  app:
    container_name: scc_app
    build: $NODE_DOCKERFILE
    env_file:
      - .env
    ports:
      - $NODE_RUN_PORTS_1
    networks:
      - $GLOBAL_NETWORK
    volumes:
      - ".$NODE_RUN_VOLUMES"
    depends_on:
      - db
volumes:
  mydb:

networks:
  scc:





