apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: nodejs-api
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: nodejs-api
    minReplicas: 2
    maxReplicas: 5
    behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
        scaleUp:
          stabilizationWindowSeconds: 5
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 10
